### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by 9MW** [abelykh0/VGA-demo-on-bluepill#1]
Good Job man.I come here from youtube 8bit guy.They plan use similar hardware to built 16bit computer,and i also have a bule pill board .So I search VGA support for this board that's led me here.I wish this can also be work on this board. link : https://www.youtube.com/watch?v=ayh0qebfD2g

**Comment by abelykh0** [comment]
I think this STM32F103 part has not enough RAM for the "computer". Please take a look at my other project using STM32F407 part that has more RAM: https://github.com/abelykh0/stm32f407-z80emu

**Comment by 9MW** [comment]
thanks for your reply.i'll take a look.:]

**Comment by junixbr** [comment]
What you think about to run a Z80 with a old arcade game in STM32F103 like a Pac-Man, for example. Is it possible? And what about simple controllers and sound?
